// client/src/pages/StudentScores.tsx
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { useLocation } from "wouter";

interface StudentScore {
  id: number;
  examTitle: string;
  score: number;
  totalPoints: number;
  submittedAt: string;
  duration: number;
  status: "passed" | "failed";
}

export default function StudentScores() {
  const [, navigate] = useLocation();
  const [selectedScore, setSelectedScore] = useState<StudentScore | null>(null);

  // Mock data
  const scores: StudentScore[] = [
    {
      id: 1,
      examTitle: "数学期中考试",
      score: 85,
      totalPoints: 100,
      submittedAt: "2026-03-30 10:30",
      duration: 120,
      status: "passed",
    },
    {
      id: 2,
      examTitle: "英语期末考试",
      score: 78,
      totalPoints: 100,
      submittedAt: "2026-03-29 14:45",
      duration: 90,
      status: "passed",
    },
    {
      id: 3,
      examTitle: "物理单元测试",
      score: 92,
      totalPoints: 100,
      submittedAt: "2026-03-28 09:20",
      duration: 60,
      status: "passed",
    },
  ];

  const statistics = {
    totalExams: scores.length,
    averageScore:
      scores.length > 0
        ? Math.round(
            (scores.reduce((sum, s) => sum + s.score, 0) / scores.length) * 100
          ) / 100
        : 0,
    passedCount: scores.filter((s) => s.status === "passed").length,
    passRate:
      scores.length > 0
        ? Math.round(
            ((scores.filter((s) => s.status === "passed").length /
              scores.length) *
              100 *
              100) /
              100
          )
        : 0,
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border/50 backdrop-blur-sm sticky top-0 z-50 bg-card/50">
        <div className="container flex items-center justify-between h-16">
          <div className="flex items-center gap-3">
            <Button
              variant="ghost"
              size="sm"
              onClick={() => navigate("/student/dashboard")}
            >
              返回
            </Button>
            <h1 className="text-lg font-bold gradient-text">我的成绩</h1>
          </div>
        </div>
      </header>

      <div className="container py-8">
        {/* Statistics */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
          <div className="card-elegant">
            <p className="text-sm text-muted-foreground mb-1">考试总数</p>
            <p className="text-3xl font-bold">{statistics.totalExams}</p>
          </div>
          <div className="card-elegant">
            <p className="text-sm text-muted-foreground mb-1">平均分</p>
            <p className="text-3xl font-bold">{statistics.averageScore}</p>
          </div>
          <div className="card-elegant">
            <p className="text-sm text-muted-foreground mb-1">及格数</p>
            <p className="text-3xl font-bold">{statistics.passedCount}</p>
          </div>
          <div className="card-elegant">
            <p className="text-sm text-muted-foreground mb-1">及格率</p>
            <p className="text-3xl font-bold">{statistics.passRate}%</p>
          </div>
        </div>

        {/* Scores List */}
        <div className="space-y-4">
          {scores.length > 0 ? (
            scores.map((score) => (
              <div
                key={score.id}
                className="card-elegant hover:shadow-md transition-shadow cursor-pointer"
                onClick={() => setSelectedScore(score)}
              >
                <div className="flex items-center justify-between">
                  <div className="flex-1">
                    <h3 className="text-lg font-bold mb-2">{score.examTitle}</h3>
                    <div className="flex items-center gap-6 text-sm text-muted-foreground">
                      <span>提交时间: {score.submittedAt}</span>
                      <span>用时: {score.duration} 分钟</span>
                    </div>
                  </div>
                  <div className="text-right">
                    <div
                      className={`text-3xl font-bold mb-2 ${
                        score.status === "passed"
                          ? "text-pink-600"
                          : "text-pink-800"
                      }`}
                    >
                      {score.score}
                    </div>
                    <div className="text-sm text-muted-foreground mb-3">
                      / {score.totalPoints}
                    </div>
                    <Button variant="outline" size="sm">
                      查看详情
                    </Button>
                  </div>
                </div>
              </div>
            ))
          ) : (
            <div className="card-elegant text-center py-12">
              <p className="text-muted-foreground mb-4">暂无考试成绩</p>
              <Button
                onClick={() => navigate("/student/dashboard")}
                className="btn-elegant-primary"
              >
                返回学生中心
              </Button>
            </div>
          )}
        </div>

        {/* Score Detail Modal */}
        {selectedScore && (
          <div className="fixed inset-0 bg-black/50 flex items-center justify-center p-4 z-50">
            <div className="card-elegant max-w-md w-full">
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-2xl font-bold">{selectedScore.examTitle}</h2>
                <button
                  onClick={() => setSelectedScore(null)}
                  className="text-muted-foreground hover:text-foreground"
                >
                  ✕
                </button>
              </div>

              <div className="space-y-4 mb-6">
                <div className="flex justify-between">
                  <span className="text-muted-foreground">成绩</span>
                  <span className="font-bold text-lg">{selectedScore.score}/{selectedScore.totalPoints}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">状态</span>
                  <span
                    className={`font-bold ${
                      selectedScore.status === "passed"
                        ? "text-pink-600"
                        : "text-pink-800"
                    }`}
                  >
                    {selectedScore.status === "passed" ? "及格" : "未及格"}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">用时</span>
                  <span className="font-bold">{selectedScore.duration} 分钟</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">提交时间</span>
                  <span className="font-bold">{selectedScore.submittedAt}</span>
                </div>
              </div>

              <div className="space-y-2">
                <Button
                  className="w-full btn-elegant-primary"
                  onClick={() => setSelectedScore(null)}
                >
                  关闭
                </Button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// client/src/views/StudentScores.vue
<template>
  <div class="min-h-screen" style="background: var(--color-background)">
    <!-- Header -->
    <header
      class="border-b sticky top-0 z-50 backdrop-blur-sm"
      style="border-color: var(--color-border); background: rgba(255,255,255,0.8)"
    >
      <div class="container flex items-center justify-between h-16">
        <div class="flex items-center gap-3">
          <el-button text @click="$router.push('/student/dashboard')">
            <el-icon class="mr-1"><ArrowLeft /></el-icon>
            返回
          </el-button>
          <h1 class="text-lg font-bold gradient-text">我的成绩</h1>
        </div>
      </div>
    </header>

    <div class="container py-8">
      <!-- Statistics -->
      <div class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
        <div v-for="stat in statistics" :key="stat.label" class="card-elegant">
          <p class="text-sm mb-1" style="color: var(--color-text-secondary)">{{ stat.label }}</p>
          <p class="text-3xl font-bold">{{ stat.value }}</p>
        </div>
      </div>

      <!-- Loading -->
      <div v-if="loading" class="card-elegant text-center py-12">
        <el-icon class="is-loading" :size="32" style="color: #ec4899"><Loading /></el-icon>
        <p class="mt-4" style="color: var(--color-text-secondary)">正在加载成绩数据...</p>
      </div>

      <!-- Empty -->
      <div v-else-if="scores.length === 0" class="card-elegant text-center py-12">
        <el-icon :size="48" style="color: var(--color-border)"><DataAnalysis /></el-icon>
        <p class="mt-4 mb-4" style="color: var(--color-text-secondary)">暂无考试成绩</p>
        <el-button
          type="primary"
          style="background: linear-gradient(135deg, #ec4899, #db2777); border: none"
          @click="$router.push('/student/dashboard')"
        >
          返回学生中心
        </el-button>
      </div>

      <!-- Scores List -->
      <div v-else class="space-y-4">
        <div
          v-for="score in scores"
          :key="score.id"
          class="card-elegant hover:shadow-md transition-shadow cursor-pointer"
          @click="selectedScore = score"
        >
          <div class="flex items-center justify-between">
            <div class="flex-1">
              <h3 class="text-lg font-bold mb-2">{{ score.examTitle }}</h3>
              <div class="flex items-center gap-6 text-sm" style="color: var(--color-text-secondary)">
                <span>
                  <el-icon class="mr-1"><Clock /></el-icon>
                  提交时间: {{ score.submittedAt }}
                </span>
                <span>用时: {{ score.duration }} 分钟</span>
              </div>
            </div>
            <div class="text-right">
              <div class="text-3xl font-bold mb-1" :style="{ color: score.status === 'passed' ? '#22c55e' : '#ef4444' }">
                {{ score.score }}
              </div>
              <div class="text-sm mb-3" style="color: var(--color-text-secondary)">
                / {{ score.totalPoints }}
              </div>
              <el-tag :type="score.status === 'passed' ? 'success' : 'danger'" effect="plain">
                {{ score.status === "passed" ? "及格" : "未及格" }}
              </el-tag>
            </div>
          </div>
        </div>
      </div>

      <!-- Score Detail Dialog -->
      <el-dialog
        v-model="showDetail"
        :title="selectedScore?.examTitle"
        width="420px"
        destroy-on-close
      >
        <div v-if="selectedScore" class="space-y-4">
          <div class="flex justify-between text-sm">
            <span style="color: var(--color-text-secondary)">成绩</span>
            <span class="font-bold text-lg">{{ selectedScore.score }}/{{ selectedScore.totalPoints }}</span>
          </div>
          <div class="flex justify-between text-sm">
            <span style="color: var(--color-text-secondary)">状态</span>
            <el-tag :type="selectedScore.status === 'passed' ? 'success' : 'danger'" size="small">
              {{ selectedScore.status === "passed" ? "及格" : "未及格" }}
            </el-tag>
          </div>
          <div class="flex justify-between text-sm">
            <span style="color: var(--color-text-secondary)">用时</span>
            <span class="font-medium">{{ selectedScore.duration }} 分钟</span>
          </div>
          <div class="flex justify-between text-sm">
            <span style="color: var(--color-text-secondary)">提交时间</span>
            <span class="font-medium">{{ selectedScore.submittedAt }}</span>
          </div>
        </div>
        <template #footer>
          <el-button type="primary" @click="showDetail = false">关闭</el-button>
        </template>
      </el-dialog>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted } from "vue";
import { ArrowLeft, Loading, DataAnalysis, Clock } from "@element-plus/icons-vue";
import { scoresApi } from "../api";
import type { StudentScore } from "../types";

const scores = ref<StudentScore[]>([]);
const loading = ref(true);
const selectedScore = ref<StudentScore | null>(null);

const showDetail = computed({
  get: () => !!selectedScore.value,
  set: (val) => { if (!val) selectedScore.value = null; },
});

const statistics = computed(() => {
  const data = scores.value;
  return [
    { label: "考试总数", value: data.length },
    {
      label: "平均分",
      value: data.length > 0 ? Math.round(data.reduce((s, r) => s + r.score, 0) / data.length) : 0,
    },
    { label: "及格数", value: data.filter((r) => r.status === "passed").length },
    {
      label: "及格率",
      value: data.length > 0
        ? Math.round((data.filter((r) => r.status === "passed").length / data.length) * 100) + "%"
        : "0%",
    },
  ];
});

onMounted(async () => {
  loading.value = true;
  try {
    scores.value = await scoresApi.student();
  } catch {
    scores.value = [];
  } finally {
    loading.value = false;
  }
});
</script>
