// client/src/pages/StudentExam.tsx
import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { useLocation } from "wouter";

interface Question {
  id: number;
  title: string;
  type: "single" | "multiple" | "trueFalse" | "fillBlank";
  options?: Record<string, string>;
  points: number;
}

export default function StudentExam() {
  const [, navigate] = useLocation();
  const [timeLeft, setTimeLeft] = useState(3600); // 60 minutes
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [answers, setAnswers] = useState<Record<number, string>>({});
  const [submitted, setSubmitted] = useState(false);

  const questions: Question[] = [
    {
      id: 1,
      title: "什么是在线考试系统？",
      type: "single",
      options: {
        A: "一个用于组织线上考试的平台",
        B: "一个社交媒体应用",
        C: "一个文件存储服务",
        D: "一个视频播放器",
      },
      points: 5,
    },
    {
      id: 2,
      title: "以下哪些是在线考试系统的功能？（多选）",
      type: "multiple",
      options: {
        A: "题库管理",
        B: "试卷发布",
        C: "成绩查看",
        D: "视频编辑",
      },
      points: 10,
    },
    {
      id: 3,
      title: "在线考试系统可以帮助教师节省时间。",
      type: "trueFalse",
      points: 5,
    },
  ];

  // Timer effect
  useEffect(() => {
    const timer = setInterval(() => {
      setTimeLeft((prev) => {
        if (prev <= 1) {
          clearInterval(timer);
          handleSubmit();
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    return () => clearInterval(timer);
  }, []);

  const formatTime = (seconds: number) => {
    const hours = Math.floor(seconds / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    const secs = seconds % 60;
    return `${hours.toString().padStart(2, "0")}:${minutes
      .toString()
      .padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
  };

  const handleAnswer = (value: string) => {
    setAnswers({
      ...answers,
      [currentQuestion]: value,
    });
  };

  const handleSubmit = () => {
    setSubmitted(true);
  };

  const handleFinish = () => {
    navigate("/student/dashboard");
  };

  const calculateScore = () => {
    let score = 0;
    questions.forEach((q, idx) => {
      if (answers[idx]) {
        score += q.points;
      }
    });
    return Math.round((score / questions.reduce((sum, q) => sum + q.points, 0)) * 100);
  };

  if (submitted) {
    const score = calculateScore();
    return (
      <div className="min-h-screen bg-background flex items-center justify-center p-4">
        <div className="card-elegant max-w-md w-full text-center">
          <div className="mb-6">
            <div className="w-20 h-20 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
              <span className="text-4xl font-bold text-primary">{score}</span>
            </div>
            <h1 className="text-2xl font-bold mb-2">考试完成</h1>
            <p className="text-muted-foreground">
              您的成绩已提交，感谢您的参与！
            </p>
          </div>

          <div className="space-y-3 mb-6 text-left">
            <div className="flex justify-between">
              <span className="text-muted-foreground">总题数</span>
              <span className="font-medium">{questions.length}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">答题数</span>
              <span className="font-medium">
                {Object.keys(answers).length}
              </span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">得分</span>
              <span className="font-medium text-primary text-lg">{score}</span>
            </div>
          </div>

          <Button
            onClick={handleFinish}
            className="w-full btn-elegant-primary"
          >
            返回学生中心
          </Button>
        </div>
      </div>
    );
  }

  const question = questions[currentQuestion];
  const isTimeWarning = timeLeft < 300; // 5 minutes

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border/50 backdrop-blur-sm sticky top-0 z-50 bg-card/50">
        <div className="container flex items-center justify-between h-16">
          <div className="flex items-center gap-2">
            <h1 className="text-lg font-bold gradient-text">在线考试</h1>
          </div>
          <div
            className={`flex items-center gap-2 px-4 py-2 rounded-lg ${
              isTimeWarning
                ? "bg-pink-200 text-pink-800"
                : "bg-primary/10 text-primary"
            }`}
          >
            <span className="font-semibold">剩余 {formatTime(timeLeft)}</span>
          </div>
        </div>
      </header>

      <div className="container py-8">
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
          {/* Main Content */}
          <div className="lg:col-span-3">
            <div className="card-elegant">
              {/* Question */}
              <div className="mb-8">
                <div className="flex items-center justify-between mb-4">
                  <h2 className="text-xl font-bold">
                    第 {currentQuestion + 1} 题 / 共 {questions.length} 题
                  </h2>
                  <span className="text-sm bg-primary/10 text-primary px-3 py-1 rounded">
                    {question.points} 分
                  </span>
                </div>

                <p className="text-lg mb-6 leading-relaxed">
                  {question.title}
                </p>

                {/* Options */}
                {question.type === "single" && (
                  <div className="space-y-3">
                    {Object.entries(question.options || {}).map(([key, value]) => (
                      <label
                        key={key}
                        className="flex items-center p-4 border-2 border-border rounded-lg cursor-pointer hover:bg-primary/5 transition-colors"
                      >
                        <input
                          type="radio"
                          name={`question-${currentQuestion}`}
                          value={key}
                          checked={answers[currentQuestion] === key}
                          onChange={(e) => handleAnswer(e.target.value)}
                          className="w-4 h-4 cursor-pointer"
                        />
                        <span className="ml-3 font-medium">{key}.</span>
                        <span className="ml-2">{value}</span>
                      </label>
                    ))}
                  </div>
                )}

                {question.type === "multiple" && (
                  <div className="space-y-3">
                    {Object.entries(question.options || {}).map(([key, value]) => (
                      <label
                        key={key}
                        className="flex items-center p-4 border-2 border-border rounded-lg cursor-pointer hover:bg-primary/5 transition-colors"
                      >
                        <input
                          type="checkbox"
                          value={key}
                          checked={
                            answers[currentQuestion]?.includes(key) || false
                          }
                          onChange={(e) => {
                            const current = answers[currentQuestion] || "";
                            if (e.target.checked) {
                              handleAnswer(current + key);
                            } else {
                              handleAnswer(
                                current.replace(key, "")
                              );
                            }
                          }}
                          className="w-4 h-4 cursor-pointer"
                        />
                        <span className="ml-3 font-medium">{key}.</span>
                        <span className="ml-2">{value}</span>
                      </label>
                    ))}
                  </div>
                )}

                {question.type === "trueFalse" && (
                  <div className="space-y-3">
                    {["正确", "错误"].map((value, idx) => (
                      <label
                        key={idx}
                        className="flex items-center p-4 border-2 border-border rounded-lg cursor-pointer hover:bg-primary/5 transition-colors"
                      >
                        <input
                          type="radio"
                          name={`question-${currentQuestion}`}
                          value={value}
                          checked={answers[currentQuestion] === value}
                          onChange={(e) => handleAnswer(e.target.value)}
                          className="w-4 h-4 cursor-pointer"
                        />
                        <span className="ml-3">{value}</span>
                      </label>
                    ))}
                  </div>
                )}

                {question.type === "fillBlank" && (
                  <input
                    type="text"
                    value={answers[currentQuestion] || ""}
                    onChange={(e) => handleAnswer(e.target.value)}
                    placeholder="请输入答案..."
                    className="w-full px-4 py-3 border-2 border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-primary"
                  />
                )}
              </div>

              {/* Navigation */}
              <div className="flex gap-3 justify-between pt-6 border-t border-border/50">
                <Button
                  onClick={() =>
                    setCurrentQuestion(Math.max(0, currentQuestion - 1))
                  }
                  disabled={currentQuestion === 0}
                  variant="outline"
                >
                  上一题
                </Button>

                <div className="flex gap-2">
                  <Button
                    onClick={() =>
                      setCurrentQuestion(
                        Math.min(questions.length - 1, currentQuestion + 1)
                      )
                    }
                    disabled={currentQuestion === questions.length - 1}
                    variant="outline"
                  >
                    下一题
                  </Button>

                  {currentQuestion === questions.length - 1 && (
                    <Button
                      onClick={handleSubmit}
                      className="btn-elegant-primary"
                    >
                      提交答卷
                    </Button>
                  )}
                </div>
              </div>
            </div>
          </div>

          {/* Sidebar */}
          <div className="lg:col-span-1">
            <div className="card-elegant sticky top-24">
              <h3 className="font-bold mb-4">答题进度</h3>

              {isTimeWarning && (
                <div className="mb-4 p-3 bg-pink-100 border border-pink-300 rounded-lg">
                  <p className="text-sm text-pink-800">
                    时间即将结束，请尽快提交答卷
                  </p>
                </div>
              )}

              <div className="grid grid-cols-4 gap-2">
                {questions.map((_, idx) => (
                  <button
                    key={idx}
                    onClick={() => setCurrentQuestion(idx)}
                    className={`aspect-square rounded-lg font-medium transition-colors ${
                      idx === currentQuestion
                        ? "bg-primary text-primary-foreground"
                        : answers[idx]
                        ? "bg-pink-100 text-pink-700"
                        : "bg-background border border-border/50 text-muted-foreground hover:border-primary"
                    }`}
                  >
                    {idx + 1}
                  </button>
                ))}
              </div>

              <div className="mt-4 pt-4 border-t border-border/50 space-y-2 text-sm">
                <div className="flex items-center gap-2">
                  <div className="w-3 h-3 rounded bg-pink-100 border border-pink-300"></div>
                  <span>已答题</span>
                </div>
                <div className="flex items-center gap-2">
                  <div className="w-3 h-3 rounded bg-background border border-border/50"></div>
                  <span>未答题</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// client/src/views/StudentExam.vue
<template>
  <div class="min-h-screen" style="background: var(--color-background)">
    <!-- Submitted Result -->
    <div v-if="submitted" class="min-h-screen flex items-center justify-center p-4">
      <div class="card-elegant max-w-md w-full text-center animate-scale-in">
        <div class="mb-6">
          <div
            class="w-24 h-24 rounded-full flex items-center justify-center mx-auto mb-4"
            style="background: linear-gradient(135deg, rgba(249,168,212,0.1), rgba(236,72,153,0.1))"
          >
            <span class="text-4xl font-black gradient-text">{{ submitResult.score }}</span>
          </div>
          <h1 class="text-2xl font-bold mb-2">考试完成</h1>
          <p style="color: var(--color-text-secondary)">您的成绩已提交！</p>
        </div>

        <div class="space-y-3 mb-6 text-left p-4 rounded-xl" style="background: var(--color-muted)">
          <div class="flex justify-between text-sm">
            <span style="color: var(--color-text-secondary)">总题数</span>
            <span class="font-medium">{{ questions.length }}</span>
          </div>
          <div class="flex justify-between text-sm">
            <span style="color: var(--color-text-secondary)">答题数</span>
            <span class="font-medium">{{ Object.keys(answers).length }}</span>
          </div>
          <div class="flex justify-between text-sm">
            <span style="color: var(--color-text-secondary)">得分</span>
            <span class="font-medium text-lg" style="color: #f9a8d4">
              {{ submitResult.score }} / {{ submitResult.totalPoints }}
            </span>
          </div>
          <div class="flex justify-between text-sm">
            <span style="color: var(--color-text-secondary)">结果</span>
            <el-tag :type="submitResult.score >= submitResult.passingScore ? 'success' : 'danger'">
              {{ submitResult.score >= submitResult.passingScore ? "及格" : "未及格" }}
            </el-tag>
          </div>
        </div>

        <el-button type="primary" class="w-full" @click="$router.push('/student/dashboard')">
          返回学生中心
        </el-button>
      </div>
    </div>

    <!-- Exam Interface -->
    <template v-else>
      <!-- Header -->
      <header
        class="border-b sticky top-0 z-50 backdrop-blur-sm"
        style="border-color: var(--color-border); background: rgba(255,255,255,0.8)"
      >
        <div class="container flex items-center justify-between h-16">
          <div class="flex items-center gap-2">
            <h1 class="text-lg font-bold gradient-text">
              {{ examInfo?.title || "在线考试" }}
            </h1>
          </div>
          <div
            class="flex items-center gap-2 px-4 py-2 rounded-lg"
            :style="{
              background: isTimeWarning ? 'rgba(236,72,153,0.15)' : 'rgba(249,168,212,0.1)',
              color: isTimeWarning ? '#db2777' : '#f9a8d4',
            }"
          >
            <el-icon><Clock /></el-icon>
            <span class="font-semibold tabular-nums">{{ formatTime(timeLeft) }}</span>
          </div>
        </div>
      </header>

      <!-- Loading -->
      <div v-if="loading" class="flex items-center justify-center py-32">
        <div class="text-center">
          <el-icon class="is-loading" :size="40" style="color: #f9a8d4"><Loading /></el-icon>
          <p class="mt-4" style="color: var(--color-text-secondary)">正在加载考试...</p>
        </div>
      </div>

      <!-- No Exam Selected -->
      <div v-else-if="!examId" class="flex items-center justify-center py-32">
        <div class="card-elegant max-w-md w-full text-center">
          <el-icon :size="48" style="color: var(--color-border)"><Notebook /></el-icon>
          <h3 class="text-lg font-semibold mt-4 mb-2">演示模式</h3>
          <p class="mb-6" style="color: var(--color-text-secondary)">
            当前为演示考试，包含示例题目
          </p>
          <el-button type="primary" @click="startDemoExam">开始演示</el-button>
        </div>
      </div>

      <!-- Exam loaded but no questions -->
      <div v-else-if="examId && questions.length === 0" class="flex items-center justify-center py-32">
        <div class="card-elegant max-w-md w-full text-center">
          <el-icon :size="48" style="color: var(--color-border)"><Notebook /></el-icon>
          <h3 class="text-lg font-semibold mt-4 mb-2">该考试暂无题目</h3>
          <p class="mb-6" style="color: var(--color-text-secondary)">此考试尚未添加题目，请联系教师</p>
          <el-button @click="$router.push('/student/dashboard')">返回学生中心</el-button>
        </div>
      </div>

      <!-- Exam Content -->
      <div v-else-if="questions.length > 0" class="container py-8">
        <div class="grid grid-cols-1 lg:grid-cols-4 gap-8">
          <!-- Main Content -->
          <div class="lg:col-span-3">
            <div class="card-elegant">
              <div class="mb-8">
                <div class="flex items-center justify-between mb-4">
                  <h2 class="text-xl font-bold">
                    第 {{ currentQuestion + 1 }} 题 / 共 {{ questions.length }} 题
                  </h2>
                  <el-tag effect="plain">{{ Number(questions[currentQuestion].points) }} 分</el-tag>
                </div>

                <p class="text-lg mb-6 leading-relaxed">{{ questions[currentQuestion].title }}</p>

                <!-- Single Choice -->
                <div v-if="questions[currentQuestion].type === 'single'" class="space-y-3">
                  <el-radio-group
                    :model-value="answers[questions[currentQuestion].id]"
                    @update:model-value="setAnswer(questions[currentQuestion].id, $event)"
                  >
                    <div
                      v-for="(text, key) in (questions[currentQuestion].options || {})"
                      :key="key"
                      class="flex items-center p-4 rounded-xl border-2 cursor-pointer transition-all mb-3"
                      :style="{
                        borderColor: answers[questions[currentQuestion].id] === key ? '#f9a8d4' : 'var(--color-border)',
                        background: answers[questions[currentQuestion].id] === key ? 'rgba(249,168,212,0.05)' : 'transparent',
                      }"
                    >
                      <el-radio :value="key">
                        <span class="font-medium">{{ key }}.</span>
                        <span class="ml-2">{{ text }}</span>
                      </el-radio>
                    </div>
                  </el-radio-group>
                </div>

                <!-- Multiple Choice -->
                <div v-else-if="questions[currentQuestion].type === 'multiple'" class="space-y-3">
                  <el-checkbox-group
                    :model-value="currentMultipleAnswers"
                    @update:model-value="setMultipleAnswers(questions[currentQuestion].id, $event)"
                  >
                    <div
                      v-for="(text, key) in (questions[currentQuestion].options || {})"
                      :key="key"
                      class="flex items-center p-4 rounded-xl border-2 cursor-pointer transition-all mb-3"
                      :style="{
                        borderColor: currentMultipleAnswers.includes(String(key)) ? '#f9a8d4' : 'var(--color-border)',
                        background: currentMultipleAnswers.includes(String(key)) ? 'rgba(249,168,212,0.05)' : 'transparent',
                      }"
                    >
                      <el-checkbox :value="key">
                        <span class="font-medium">{{ key }}.</span>
                        <span class="ml-2">{{ text }}</span>
                      </el-checkbox>
                    </div>
                  </el-checkbox-group>
                </div>

                <!-- True/False -->
                <div v-else-if="questions[currentQuestion].type === 'trueFalse'" class="space-y-3">
                  <el-radio-group
                    :model-value="answers[questions[currentQuestion].id]"
                    @update:model-value="setAnswer(questions[currentQuestion].id, $event)"
                  >
                    <div
                      v-for="(text, key) in (questions[currentQuestion].options || {})"
                      :key="key"
                      class="flex items-center p-4 rounded-xl border-2 cursor-pointer transition-all mb-3"
                      :style="{
                        borderColor: answers[questions[currentQuestion].id] === key ? '#f9a8d4' : 'var(--color-border)',
                        background: answers[questions[currentQuestion].id] === key ? 'rgba(249,168,212,0.05)' : 'transparent',
                      }"
                    >
                      <el-radio :value="key">
                        <span class="font-medium">{{ key }}.</span>
                        <span class="ml-2">{{ text }}</span>
                      </el-radio>
                    </div>
                  </el-radio-group>
                </div>

                <!-- Fill Blank -->
                <div v-else-if="questions[currentQuestion].type === 'fillBlank'">
                  <el-input
                    v-model="answers[questions[currentQuestion].id]"
                    placeholder="请输入答案..."
                    size="large"
                  />
                </div>
              </div>

              <!-- Navigation -->
              <div class="flex gap-3 justify-between pt-6" style="border-top: 1px solid var(--color-border)">
                <el-button
                  :disabled="currentQuestion === 0"
                  @click="currentQuestion--"
                >
                  上一题
                </el-button>
                <div class="flex gap-2">
                  <el-button
                    v-if="currentQuestion < questions.length - 1"
                    @click="currentQuestion++"
                  >
                    下一题
                  </el-button>
                  <el-button
                    v-if="currentQuestion === questions.length - 1"
                    type="primary"
                    @click="handleSubmit"
                  >
                    提交答卷
                  </el-button>
                </div>
              </div>
            </div>
          </div>

          <!-- Sidebar -->
          <div class="lg:col-span-1">
            <div class="card-elegant sticky top-24">
              <h3 class="font-bold mb-4">答题进度</h3>

              <el-alert
                v-if="isTimeWarning"
                title="时间即将结束，请尽快提交答卷"
                type="warning"
                :closable="false"
                class="mb-4"
              />

              <div class="grid grid-cols-4 gap-2">
                <button
                  v-for="(_, idx) in questions"
                  :key="idx"
                  class="aspect-square rounded-lg font-medium transition-all text-sm"
                  :style="{
                    background: idx === currentQuestion
                      ? '#f9a8d4'
                      : answers[questions[idx].id]
                        ? 'rgba(249,168,212,0.15)'
                        : 'var(--color-muted)',
                    color: idx === currentQuestion
                      ? 'white'
                      : answers[questions[idx].id]
                        ? '#f9a8d4'
                        : 'var(--color-text-secondary)',
                  }"
                  @click="currentQuestion = idx"
                >
                  {{ idx + 1 }}
                </button>
              </div>

              <div class="mt-4 pt-4 space-y-2 text-sm" style="border-top: 1px solid var(--color-border)">
                <div class="flex items-center gap-2">
                  <div class="w-3 h-3 rounded" style="background: rgba(249,168,212,0.15)"></div>
                  <span>已答题</span>
                </div>
                <div class="flex items-center gap-2">
                  <div class="w-3 h-3 rounded" style="background: var(--color-muted)"></div>
                  <span>未答题</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import { ElMessage, ElMessageBox } from "element-plus";
import { Clock, Loading, Notebook } from "@element-plus/icons-vue";
import { studentExamsApi } from "../api";
import type { Question, Exam } from "../types";

const route = useRoute();
const router = useRouter();

const examId = computed(() => {
  const id = route.query.examId;
  return id ? Number(id) : null;
});

const examInfo = ref<Exam | null>(null);
const questions = ref<(Question & { order: number; examPoints: string })[]>([]);
const loading = ref(false);
const currentQuestion = ref(0);
const answers = ref<Record<number, string>>({});
const submitted = ref(false);
const timeLeft = ref(3600);
const startTime = ref("");
const timer = ref<ReturnType<typeof setInterval> | null>(null);

const submitResult = ref({ score: 0, totalPoints: 0, passingScore: 60 });

const isTimeWarning = computed(() => timeLeft.value < 300);

const formatTime = (seconds: number) => {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = seconds % 60;
  return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
};

const setAnswer = (questionId: number, value: string) => {
  answers.value[questionId] = value;
};

const currentMultipleAnswers = computed(() => {
  if (!questions.value.length) return [];
  const qId = questions.value[currentQuestion.value]?.id;
  const raw = answers.value[qId] || "";
  return raw ? raw.split("").filter(Boolean) : [];
});

const setMultipleAnswers = (questionId: number, values: string[]) => {
  answers.value[questionId] = values.sort().join("");
};

const startTimer = (durationMinutes: number) => {
  timeLeft.value = durationMinutes * 60;
  timer.value = setInterval(() => {
    timeLeft.value--;
    if (timeLeft.value <= 0) {
      if (timer.value) clearInterval(timer.value);
      submitExam();
    }
  }, 1000);
};

const loadExam = async () => {
  if (!examId.value) return;
  loading.value = true;
  try {
    const data = await studentExamsApi.getExam(examId.value);
    console.log("[DEBUG] loadExam response:", data);
    console.log("[DEBUG] questions count:", data.questions?.length);
    examInfo.value = data.exam;
    questions.value = data.questions;
    startTime.value = new Date().toISOString();
    startTimer(data.exam.duration);
  } catch {
    ElMessage.error("加载考试失败");
  } finally {
    loading.value = false;
  }
};

const startDemoExam = () => {
  questions.value = [
    {
      id: 1, type: "single", title: "什么是在线考试系统？",
      options: { A: "一个用于组织线上考试的平台", B: "一个社交媒体应用", C: "一个文件存储服务", D: "一个视频播放器" },
      correctAnswer: "A", explanation: null, difficulty: "easy", category: null, points: "5",
      createdBy: 0, createdAt: "", updatedAt: "", order: 1, examPoints: "5",
    },
    {
      id: 2, type: "multiple", title: "以下哪些是在线考试系统的功能？（多选）",
      options: { A: "题库管理", B: "试卷发布", C: "成绩查看", D: "视频编辑" },
      correctAnswer: "A,B,C", explanation: null, difficulty: "medium", category: null, points: "10",
      createdBy: 0, createdAt: "", updatedAt: "", order: 2, examPoints: "10",
    },
    {
      id: 3, type: "trueFalse", title: "在线考试系统可以帮助教师节省时间。",
      options: { A: "正确", B: "错误" }, correctAnswer: "A", explanation: null, difficulty: "easy", category: null, points: "5",
      createdBy: 0, createdAt: "", updatedAt: "", order: 3, examPoints: "5",
    },
  ];
  startTime.value = new Date().toISOString();
  startTimer(60);
};

const submitExam = async () => {
  if (timer.value) clearInterval(timer.value);

  // If we have a real exam, submit to server
  if (examId.value && examId.value < 1_000_000_000) {
    try {
      const result = await studentExamsApi.submit(examId.value, {
        answers: answers.value,
        startTime: startTime.value,
      });
      submitResult.value = {
        score: result.score,
        totalPoints: result.totalPoints,
        passingScore: Number(examInfo.value?.passingScore ?? 60),
      };
    } catch {
      // Fall through to demo scoring
      demoScore();
    }
  } else {
    demoScore();
  }

  submitted.value = true;
};

const demoScore = () => {
  let score = 0;
  questions.value.forEach((q) => {
    if (answers.value[q.id]) score += Number(q.points);
  });
  const total = questions.value.reduce((s, q) => s + Number(q.points), 0);
  submitResult.value = { score, totalPoints: total, passingScore: 60 };
};

const handleSubmit = async () => {
  try {
    await ElMessageBox.confirm("确定要提交答卷吗？提交后不可修改。", "确认提交", {
      confirmButtonText: "提交",
      cancelButtonText: "继续答题",
      type: "warning",
    });
    submitExam();
  } catch {
    // cancelled
  }
};

onMounted(() => {
  if (examId.value) {
    loadExam();
  }
});

onUnmounted(() => {
  if (timer.value) clearInterval(timer.value);
});
</script>
